name: Test JMeter Action

on:
  push:
    branches:
      - E-add-JMeter-to-CICD

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ./express/JMeter/jmeter-cw-logs/jmeter-test-plan.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Upload JMeter test results
        uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/


